import type { CollectiveEvent, Reward, Opportunity, Member, CurrentUser, Role } from "./types"

export const users: Record<Role, CurrentUser> = {
  usuario: {
    name: "Lucía Méndez",
    email: "lucia@raizverde.org",
    role: "usuario",
    streak: 3,
    points: 240,
    eventsAttended: 6,
    treesPlanted: 4,
    kgRecycled: 38,
  },
  lider: {
    name: "Mateo Ríos",
    email: "mateo@raizverde.org",
    role: "lider",
    streak: 11,
    points: 1480,
    eventsAttended: 34,
    treesPlanted: 27,
    kgRecycled: 210,
  },
  admin: {
    name: "Admin Raíz Verde",
    email: "admin@raizverde.org",
    role: "admin",
    streak: 24,
    points: 9999,
    eventsAttended: 120,
    treesPlanted: 96,
    kgRecycled: 880,
  },
}

export const events: CollectiveEvent[] = [
  {
    id: "ev-1",
    title: "Limpieza del Río Verde",
    category: "limpieza",
    date: "Sáb 14 Jun",
    time: "08:00",
    location: "Ribera Norte, Sector 3",
    description: "Jornada de limpieza de orillas y separación de residuos junto al río.",
    capacity: 40,
    enrolled: 28,
    points: 80,
    status: "abierto",
    minRole: "usuario",
    image: "/river-cleanup-volunteers.png",
  },
  {
    id: "ev-2",
    title: "Reforestación Cerro Azul",
    category: "reforestacion",
    date: "Dom 15 Jun",
    time: "07:30",
    location: "Cerro Azul, entrada sur",
    description: "Plantación de 200 árboles nativos para recuperar la ladera.",
    capacity: 60,
    enrolled: 60,
    points: 120,
    status: "lleno",
    minRole: "usuario",
    image: "/people-planting-trees-on-a-hill.png",
  },
  {
    id: "ev-3",
    title: "Punto de Reciclaje Comunitario",
    category: "reciclaje",
    date: "Mié 18 Jun",
    time: "16:00",
    location: "Plaza Central",
    description: "Acopio y clasificación de plásticos, vidrio y electrónicos.",
    capacity: 25,
    enrolled: 12,
    points: 50,
    status: "abierto",
    minRole: "usuario",
    image: "/community-recycling-station.png",
  },
  {
    id: "ev-4",
    title: "Taller: Compostaje en casa",
    category: "taller",
    date: "Vie 20 Jun",
    time: "18:00",
    location: "Cafetería Sostenible",
    description: "Aprende a transformar tus residuos orgánicos en abono.",
    capacity: 30,
    enrolled: 19,
    points: 40,
    status: "abierto",
    minRole: "usuario",
    image: "/home-composting-workshop.png",
  },
  {
    id: "ev-5",
    title: "Coordinación de Líderes Ambientales",
    category: "educacion",
    date: "Lun 23 Jun",
    time: "19:00",
    location: "Sala de juntas",
    description: "Planeación mensual de campañas. Solo líderes y administración.",
    capacity: 15,
    enrolled: 8,
    points: 100,
    status: "abierto",
    minRole: "lider",
    image: "/leadership-meeting-environmental.png",
  },
  {
    id: "ev-6",
    title: "Feria Ambiental Estatal",
    category: "educacion",
    date: "Sáb 5 Jul",
    time: "10:00",
    location: "Parque Metropolitano",
    description: "Stand del colectivo en alianza con el gobierno estatal.",
    capacity: 50,
    enrolled: 0,
    points: 90,
    status: "proximamente",
    minRole: "usuario",
    image: "/environmental-fair-outdoor.png",
  },
]

export const rewards: Reward[] = [
  {
    id: "rw-1",
    title: "Café orgánico gratis",
    description: "Un café de especialidad de origen sostenible en la cafetería.",
    cost: 80,
    category: "cafeteria",
    minRole: "usuario",
    available: true,
  },
  {
    id: "rw-2",
    title: "Combo desayuno verde",
    description: "Bowl de avena, fruta de temporada y bebida vegetal.",
    cost: 180,
    category: "cafeteria",
    minRole: "usuario",
    available: true,
  },
  {
    id: "rw-3",
    title: "Termo reutilizable Raíz Verde",
    description: "Termo de acero inoxidable con el logo del colectivo.",
    cost: 320,
    category: "merch",
    minRole: "usuario",
    available: true,
  },
  {
    id: "rw-4",
    title: "Descuento 30% mensual cafetería",
    description: "Beneficio exclusivo por mantener racha semanal activa.",
    cost: 500,
    category: "cafeteria",
    minRole: "lider",
    available: true,
  },
  {
    id: "rw-5",
    title: "Mesa de líder en cafetería",
    description: "Espacio reservado y bebida ilimitada los fines de semana.",
    cost: 900,
    category: "experiencia",
    minRole: "lider",
    available: true,
  },
  {
    id: "rw-6",
    title: "Kit de jardinería premium",
    description: "Herramientas y semillas nativas para tu huerto.",
    cost: 600,
    category: "merch",
    minRole: "usuario",
    available: false,
  },
]

export const opportunities: Opportunity[] = [
  {
    id: "op-1",
    title: "Coordinador/a de campañas de limpieza",
    org: "Secretaría de Medio Ambiente",
    type: "empleo",
    location: "Tiempo completo · Ciudad",
    description: "Convenio con el estado para liderar brigadas urbanas remuneradas.",
  },
  {
    id: "op-2",
    title: "Beca de educación ambiental",
    org: "Fundación Tierra Viva",
    type: "beca",
    location: "Híbrido · 6 meses",
    description: "Formación certificada en gestión de proyectos sostenibles.",
  },
  {
    id: "op-3",
    title: "Voluntariado internacional de reforestación",
    org: "Red Verde Latinoamérica",
    type: "voluntariado",
    location: "Presencial · Costa Rica",
    description: "Intercambio de 3 semanas con colectivos aliados de la región.",
  },
  {
    id: "op-4",
    title: "Convenio de prácticas con empresa B",
    org: "EcoLogística S.A.",
    type: "convenio",
    location: "Medio tiempo · Ciudad",
    description: "Prácticas profesionales en logística circular y residuos.",
  },
]

export const members: Member[] = [
  { id: "m-1", name: "Lucía Méndez", email: "lucia@raizverde.org", role: "usuario", streak: 3, points: 240, eventsAttended: 6, joined: "Mar 2025" },
  { id: "m-2", name: "Mateo Ríos", email: "mateo@raizverde.org", role: "lider", streak: 11, points: 1480, eventsAttended: 34, joined: "Ene 2024" },
  { id: "m-3", name: "Sofía Castro", email: "sofia@raizverde.org", role: "usuario", streak: 7, points: 620, eventsAttended: 14, joined: "Nov 2024" },
  { id: "m-4", name: "Diego Herrera", email: "diego@raizverde.org", role: "lider", streak: 9, points: 1120, eventsAttended: 29, joined: "Feb 2024" },
  { id: "m-5", name: "Valentina Cruz", email: "valentina@raizverde.org", role: "usuario", streak: 1, points: 90, eventsAttended: 2, joined: "May 2025" },
  { id: "m-6", name: "Andrés Morales", email: "andres@raizverde.org", role: "usuario", streak: 5, points: 410, eventsAttended: 9, joined: "Ene 2025" },
]

export const roleLabels: Record<Role, string> = {
  usuario: "Miembro",
  lider: "Líder Ambiental",
  admin: "Administrador",
}

export const categoryLabels: Record<CollectiveEvent["category"], string> = {
  limpieza: "Limpieza",
  reforestacion: "Reforestación",
  reciclaje: "Reciclaje",
  educacion: "Educación",
  taller: "Taller",
}
